try{
    console.log(erro);
} catch(e){
    console.log('Deu erro.');
}